[[redirects]]
  from = "/*"
  to = "/"
  status = 200

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
publish = "dist"
command = "yarn build"

# Production context: all deploys from the Production branch set in your site's deploy contexts will inherit these settings.
[context.production]
environment = { GOOGLE_TAG_MANAGER_ID = "GTM-NP4BJ8C", SENTRY_DSN = "https://a5d3ce913bdd4eb594da36387b286d83@o242378.ingest.sentry.io/5496000", SENTRY_PERF_SAMPLE_RATE = 1 }

# Specific branch context: all deploys from this specific branch will inherit these settings.
[context.staging] # 'staging' is a branch
environment = { GOOGLE_TAG_MANAGER_ID = "", SENTRY_DSN = "https://a5d3ce913bdd4eb594da36387b286d83@o242378.ingest.sentry.io/5496000", SENTRY_PERF_SAMPLE_RATE = 0 }

# Specific branch context: all deploys from this specific branch will inherit these settings.
[context.sandbox] # 'sandbox' is a branch
environment = { GOOGLE_TAG_MANAGER_ID = "", SENTRY_DSN = "https://a5d3ce913bdd4eb594da36387b286d83@o242378.ingest.sentry.io/5496000", SENTRY_PERF_SAMPLE_RATE = 0 }

# Deploy preview context: all deploys generated from a pull/merge request will inherit these settings.
[context.deploy-preview]
environment = { GOOGLE_TAG_MANAGER_ID = "", SENTRY_DSN = "", SENTRY_PERF_SAMPLE_RATE = 0 }

# Branch deploy context: all deploys that are not from a pull/merge request or from the Production branch will inherit these settings.
[context.branch-deploy]
environment = { GOOGLE_TAG_MANAGER_ID = "", SENTRY_DSN = "", SENTRY_PERF_SAMPLE_RATE = 0 }
